--These are example queries to be used in sqlite3 files generated by the python scripts

-- show the survey header information for all surveys
select *
from surveys s order by s.dateTime;

-- all distinct wifi beacons with vendor name and survey data
select distinct s.dateTime, s.longitude, s.lattitude, w.ssid, w.bssid, w.type, mv.vendorName
from wifi w
	join surveys s on s.surveyInx = w.surveyInx
	left join mac_vendor mv on substr(w.bssid, 1, 8) like mv.prefix
where w.type like 'beacon'
order by w.bssid;

-- all distinct bluetooth beacons with vendor, uuid, and survey data
select distinct s.dateTime, s.longitude, s.lattitude, b.name, b.mac, bu.uuidHex, bu.name
from btle b
	join surveys s on s.surveyInx = b.surveyInx
	left join uuid16 u on b.btInx = u.btInx
	left join bluetooth_uuids bu on u.uuid16 = bu.uuidDec
order by bu.name DESC, b.name DESC, b.mac;

-- wifi count and unique mac address (with vendor name if applicable)
select distinct count(w.bssid), w.ssid, w.bssid, mv.vendorName
from wifi w
	left join mac_vendor mv on substr(w.bssid, 1, 8) like mv.prefix
where w.type like 'beacon'
group by w.bssid
order by count(w.bssid) desc;

-- bluetooth count and unique mac address (with vendor name if applicable)
select distinct count(b.mac), b.mac, mv.vendorName
from btle b
	left join mac_vendor mv on substr(b.mac, 1, 8) like mv.prefix
group by b.mac
order by count(b.mac) desc;
